### ISSUE TITLE
QG训练营网络组第一周周记：2016年4月17日

### ISSUE THREAD

**Issue by ruiwenruiwen** [ruiwenruiwen/dairy-homework#3]
# QG训练营网络组第一周周记：2016年4月17日

## 生活随记

>   本周学习日完成（6/7）
>   本周吃肉任务完成（2/2）

>   暂且来说还是蛮充实的一周。其实似乎从三月初始直到工作室招新之后就没有不充实过了~
>    一条安分的咸鱼，突然意识到能有翻身的机会，便努力的好好学C，便让自己多看看HTML和CSS，也是突然化身成了追逐梦想的美少女了（这画风有点不大对）。

>    也是不知道什么时候开始给自己定下的一个routine，每周无论多忙都要南亭走一波。
>    是的是的，周瑞雯有云：吃好和睡好必定有一个在路上。然而常年睡不好的我便只能从肉中寻找慰藉了嘿嘿嘿...

## 学习情况

>    这周似乎是暴风雨前的宁静。训练营尚未正式开始，还是在自己慢慢的看着HTML和CSS的状态。直到周日才发现自己真的是看得太慢了……
>    也是清楚理论知识的学习是低效而缓慢的，往往实际操作中才得到更大收获。但是慢性子的瑞雯大人似乎一点也不着急掌握一些前端的入门知识呢~
>    直到周日晚上，才发现自己时日无多，临表涕零（这画风又不对劲了）。
>    这周和很多师兄师姐交流了前端的学习路线，问出了许多有帮助的书籍。也是要从网站学习赶紧跳出来进入下一个篇章了呢~
>    本周依旧是HTML和CSS的w3school上基础入门，囿于别的工作室招新，本咸鱼不安分的四处闯荡，也是仍旧把重心放在C上的一周，虽然感觉自己的链表还是乱七八糟不知道指到何处去。不过既然选择了工作室的考核，也是要更高效一点入门前端知识了。

## 一周总结

>    我似乎已经不记得本周开始之前所定的学习计划了。一是因为记忆力不大好的硬伤，而是因为之前也没有固定的定学习规划的习惯。
>    不过我觉得这一周，大概是把学习重点从C转化到前端知识的转折点吧。虽然总的花费的时间还是不多（对，我也不知道我干什么去了），但是至少比一周开始之前，还是收获了许多。
>    最大的还是学习方法的转变。在此之前，我似乎都是偏向于学习了“为什么会这样子”之后，才会步入“我该怎么做”的状态。然而第N遍强调，实践出真知！！
>    其实，工作室考核让我有一种现学现卖的感觉，那种感觉和打辩论是差不多的。查资料→理清逻辑链→实践。昨天和一个师姐交流了才发现，如果在一个时间段内快速入门的话，边实验边查资料边理清逻辑其实是更快速的。
>    此刻，打开新世纪大门，向实践飞奔。

## 存在问题

>    恩，我觉得，我最大的问题，就是——
>    我觉得蛮矫情的吧，看心情学习。虽然说代码的学习确实是要清醒的头脑，不过自己稍微困点就不想学习似乎也是太矫情了呢~
>    觉得这个倒是我一直以来拖拖拉拉慢慢悠悠的原因。
>    即便根本上是自己常年慢性子使然。不过这玩意还是可以锻炼的吧~
>    毕竟自己从上机晕翻身成一口气做六道题也是饱受磨（nue）炼（dai）才能发生转变的呀~
>    加之以自己在学习代码的道路上确实是低效的磨蹭着~

## 下周规划

>    下周，下周，下周，不能再这么拖拖拉拉呢。毕竟也是要加快进度，多做一些小实验，多敲一些代码来玩玩了。毕竟实践出真知啊~
>    尽快看看JavaScript。貌似好玩的东西都在那里~~
>    本周会是更充实的一周的感觉。
>    恩，如果能克服不耐烦和困就不学习的话，将会是自己的一大进步。
>    有什么事情，不能用一顿肉来解决呢！
>    所以，为了本周愉快的routine，继续努力翻身吧~

**Comment by LitterWorn** [comment]
学习一门知识，先学会怎么做，再去学习为什么，这样的学习效率会更快一点。
边学边动手敲是正确的，如果等你学完再去试着写demo，你会发现忘记学了什么，所以动手能力很重要
好好学习，天天向上，下次去吃肉记得带上我
